import { Button, Card, Grid, Row, Spacer, Text } from "@nextui-org/react";
import Head from "next/head";
import React, { useEffect, useState } from "react";
import NewMeetupForm from "../../components/Forms/NewMeetupForm";
import NavBar from "../../components/NavBar";
import Modal from "../../components/UI/Modal";
import { useQuery } from "@apollo/client";
import { MEETUP_LIST } from "../../graphql/queries";
import { useAuthenticationStatus } from "@nhost/nextjs";
import { useRouter } from "next/router";

interface IMeetupProps {
  meetup_list: {
    meetup_address: string;
    meetup_description: string;
    meetup_image: string;
    meetup_title: string;
    uuid: string;
  }[];
}

const MeetUps = () => {
  const [open, setOpen] = useState<boolean>(false);
  const [meetupData, setMeetupData] = useState<IMeetupProps | null>(null);
  const { data } = useQuery(MEETUP_LIST);

  const router = useRouter();

  useEffect(() => {
    setMeetupData(data);
  }, [data]);

  const { isAuthenticated } = useAuthenticationStatus();

  if (!isAuthenticated) {
    router.push("/");
  }

  return (
    <>
      <Head>
        <title>Let&apos;s Link | All Meetups</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Row css={{ my: 20 }} justify="center">
        <Button shadow color="secondary" auto onClick={() => setOpen(true)}>
          Add New Meetup
        </Button>
      </Row>

      <Modal
        onOpen={open}
        onClose={() => setOpen(false)}
        modalTitle="Add New Meetup"
      >
        <NewMeetupForm onClose={() => setOpen(false)} />
      </Modal>
      <Grid.Container gap={2} justify="center">
        {meetupData?.meetup_list.map((item) => (
          <Grid xs={7} sm={5} key={item.uuid}>
            <Card css={{ w: "100%", h: "400px" }}>
              <Card.Body css={{ p: 0 }}>
                <Card.Image
                  src="https://nextui.org/images/card-example-5.jpeg"
                  objectFit="cover"
                  width="100%"
                  height="100%"
                  alt="Relaxing app background"
                />
              </Card.Body>
              <Card.Footer
                css={{
                  position: "absolute",
                  bgBlur: "#0f111466",
                  borderTop: "$borderWeights$light solid $gray800",
                  bottom: 0,
                  zIndex: 1,
                }}
              >
                <div className="flex flex-col justify-center items-center w-full">
                  <Text css={{ color: "white" }}>{item.meetup_title}</Text>
                  <Spacer />
                  <Text css={{ color: "white" }}>{item.meetup_address}</Text>
                  <Spacer />
                  <Button
                    flat
                    auto
                    rounded
                    css={{ color: "#94f9f0", bg: "#94f9f026" }}
                  >
                    Show Details
                  </Button>
                </div>
              </Card.Footer>
            </Card>
          </Grid>
        ))}
      </Grid.Container>
    </>
  );
};

export default MeetUps;
