import { Button, Text } from "@nextui-org/react";
import Head from "next/head";
import React, { useState } from "react";
import NewMeetupForm from "../../components/Forms/NewMeetupForm";
import NavBar from "../../components/NavBar";
import Modal from "../../components/UI/Modal";

const MeetUps = () => {
  const [open, setOpen] = useState<boolean>(false);
  return (
    <>
      <Head>
        <title>Let&apos;s Link | All Meetups</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <Button shadow color="secondary" auto onClick={() => setOpen(true)}>
        Add New Meetup
      </Button>
      <Modal
        onOpen={open}
        onClose={() => setOpen(false)}
        modalTitle="Add New Meetup"
      >
        <NewMeetupForm />
      </Modal>
    </>
  );
};

export default MeetUps;
