import React, { useState } from "react";
import { useSignInEmailPassword } from "@nhost/nextjs";
import {
  Button,
  Checkbox,
  Grid,
  Input,
  Row,
  Text,
  Card,
} from "@nextui-org/react";

import { useRouter } from "next/router";
import Head from "next/head";
import NavBar from "../../components/NavBar";
import LoginSvg from "../../components/UI/SVG/login";

const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const { signInEmailPassword, isLoading, isSuccess, isError, error } =
    useSignInEmailPassword();

  const router = useRouter();

  const handleOnSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault();
    try {
      await signInEmailPassword(email, password);
    } catch (error) {
      console.log(error);
    }
  };
  if (isError) {
  }
  if (isSuccess) {
    router.push("/all-meetups");
    return null;
  }

  return (
    <>
      <Head>
        <title>Let&apos;s Link | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <Grid.Container gap={2} justify="center">
        <Grid xs={6} justify={"center"}>
          <Card css={{ justifyContent: "center", alignItems: "center" }}>
            <Card.Header css={{ justifyContent: "center", py: 30 }}>
              <Text h3> Login To Account</Text>
            </Card.Header>
            <form onSubmit={handleOnSubmit}>
              <Input
                clearable
                bordered
                fullWidth
                color="primary"
                size="lg"
                placeholder="Email"
                onChange={(e) => setEmail(e.target.value)}
                css={{ mb: 20 }}
              />

              <Input
                clearable
                bordered
                fullWidth
                color="primary"
                size="lg"
                placeholder="Password"
                onChange={(e) => setPassword(e.target.value)}
                css={{ mb: 20 }}
              />
              <Row justify="space-between" css={{ mb: 20 }}>
                <Checkbox>
                  <Text size={14}>Remember me</Text>
                </Checkbox>
                <Text size={14}>Forgot password?</Text>
              </Row>
              <Row justify="center">
                <Button type="submit" color="secondary" shadow>
                  Login
                </Button>
              </Row>
            </form>
            <Card.Footer css={{ justifyContent: "center", mt: 20 }}>
              Doesn&apos;t have an account?{"  "}
              <Text
                onClick={() => router.push("/auth/sign-up")}
                color="secondary"
                as={"span"}
                css={{ cursor: "pointer" }}
              >
                SignUp
              </Text>
            </Card.Footer>
          </Card>
        </Grid>
        <Grid xs={6}>
          <LoginSvg />
        </Grid>
      </Grid.Container>
    </>
  );
};

export default Login;
