import React, { useState } from "react";
import { useSignInEmailPassword } from "@nhost/nextjs";
import {
  Button,
  Checkbox,
  Grid,
  Input,
  Row,
  Text,
  Card,
  Spacer,
  Loading,
} from "@nextui-org/react";

import { useRouter } from "next/router";
import Head from "next/head";
import NavBar from "../../components/NavBar";
import LoginSvg from "../../components/UI/SVG/login";
import ForgotPassword from "../../components/ForgotPassword";
import toast, { Toaster } from "react-hot-toast";

const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const {
    signInEmailPassword,
    isLoading,
    isSuccess,
    isError,
    error: errorMessage,
  } = useSignInEmailPassword();

  const router = useRouter();

  console.log("Error :", errorMessage?.message);

  const handleOnSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault();
    try {
      await signInEmailPassword(email, password);
    } catch (error) {
      //@ts-ignore
      toast.error(errorMessage?.message);
    }
  };

  if (isSuccess) {
    router.push("/all-meetups");
    return null;
  }

  return (
    <>
      <Toaster />
      <Head>
        <title>Let&apos;s Link | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <Grid.Container gap={2} justify="center">
        <Grid xs={6} justify={"center"}>
          <Card css={{ justifyContent: "center", alignItems: "center" }}>
            <Card.Header css={{ justifyContent: "center", py: 30 }}>
              <Text h3> Login To Account</Text>
            </Card.Header>
            <form onSubmit={handleOnSubmit}>
              <Input
                clearable
                bordered
                fullWidth
                color="primary"
                size="lg"
                placeholder="Email"
                onChange={(e) => setEmail(e.target.value)}
                css={{ mb: 20 }}
              />

              <Input
                clearable
                bordered
                fullWidth
                color="primary"
                size="lg"
                placeholder="Password"
                onChange={(e) => setPassword(e.target.value)}
                css={{ mb: 20 }}
              />
              <Row justify="space-between" css={{ mb: 20 }}>
                <Checkbox>
                  <Text size={14}>Remember me</Text>
                </Checkbox>
                <ForgotPassword />
              </Row>
              <Row justify="center">
                <Button type="submit" color="secondary" shadow>
                  {isLoading ? (
                    <Row justify="space-evenly">
                      <Text color={"white"}>Signing In</Text>
                      <Spacer />
                      <Loading type="spinner" color={"white"} size="lg" />
                    </Row>
                  ) : (
                    "Login"
                  )}
                </Button>
              </Row>
            </form>
            <Card.Footer css={{ justifyContent: "center", mt: 20 }}>
              Doesn&apos;t have an account?{"  "}
              <Text
                onClick={() => router.push("/auth/sign-up")}
                color="secondary"
                as={"span"}
                css={{ cursor: "pointer" }}
              >
                SignUp
              </Text>
            </Card.Footer>
          </Card>
        </Grid>
        <Grid xs={6}>
          <LoginSvg />
        </Grid>
      </Grid.Container>
    </>
  );
};

export default Login;
