import React, { useState } from "react";
import { Button, Card, Grid, Input, Row, Text } from "@nextui-org/react";
import { useSignUpEmailPassword } from "@nhost/nextjs";

import { useRouter } from "next/router";
import Head from "next/head";
import NavBar from "../../components/NavBar";
import LoginSvg from "../../components/UI/SVG/login";

const SignUp = () => {
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const router = useRouter();
  const {
    signUpEmailPassword,
    isLoading,
    isSuccess,
    needsEmailVerification,
    isError,
    error,
  } = useSignUpEmailPassword();
  const handleOnSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault();

    await signUpEmailPassword(email, password, {
      displayName: `${firstName} ${lastName}`.trim(),
      metadata: {
        firstName,
        lastName,
      },
    });
  };
  if (isSuccess) {
    router.push("/all-meetups");
    return null;
  }
  const closeHandler = () => {
    setIsOpen(false);
  };
  return (
    <>
      <Head>
        <title>Let&apos;s Link | Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <Grid.Container gap={2} justify="center">
        <Grid xs={6} justify={"center"}>
          <Card
            css={{
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            <Card.Header css={{ justifyContent: "center" }}>
              <Text h2> Sign Up An Account</Text>
            </Card.Header>
            <div style={{ maxWidth: "50%" }}>
              <form onSubmit={handleOnSubmit}>
                <Input
                  clearable
                  bordered
                  fullWidth
                  color="primary"
                  size="lg"
                  placeholder="First Name"
                  onChange={(e) => setFirstName(e.target.value)}
                  css={{ mb: 20 }}
                />
                <Input
                  clearable
                  bordered
                  fullWidth
                  color="primary"
                  size="lg"
                  placeholder="Last Name"
                  onChange={(e) => setLastName(e.target.value)}
                  css={{ mb: 20 }}
                />
                <Input
                  clearable
                  bordered
                  fullWidth
                  color="primary"
                  size="lg"
                  placeholder="Email"
                  onChange={(e) => setEmail(e.target.value)}
                  css={{ mb: 20 }}
                />
                <Input
                  clearable
                  bordered
                  fullWidth
                  color="primary"
                  size="lg"
                  placeholder="Password"
                  onChange={(e) => setPassword(e.target.value)}
                  css={{ mb: 20 }}
                />
                <Row justify="center">
                  <Button
                    type="submit"
                    color="secondary"
                    shadow
                    onClick={closeHandler}
                  >
                    Sign Up
                  </Button>
                </Row>
              </form>
            </div>
            <Card.Footer css={{ justifyContent: "center", mt: 20 }}>
              Already a user?{" "}
              <Text
                onClick={() => router.push("/auth/login")}
                color="secondary"
                as={"span"}
                css={{ cursor: "pointer" }}
              >
                Login
              </Text>
            </Card.Footer>
          </Card>
        </Grid>
        <Grid xs={6}>
          <LoginSvg />
        </Grid>
      </Grid.Container>
    </>
  );
};

export default SignUp;
