import Head from "next/head";
import React from "react";
import NavBar from "../components/NavBar";

const About = () => {
  return (
    <>
      <Head>
        <title>Let&apos;s Link | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
    </>
  );
};

export default About;
