import { Button, Card, Grid, Input, Row, Text } from "@nextui-org/react";
import { useChangePassword } from "@nhost/nextjs";
import Head from "next/head";
import React, { useState } from "react";
import toast, { Toaster } from "react-hot-toast";
import NavBar from "../../components/NavBar";
import LoginSvg from "../../components/UI/SVG/login";

const ChangePassword = () => {
  const [newPassword, setNewPassword] = useState<string>("");
  const [confirmedPassword, setConfirmedPassword] = useState<string>("");
  const { changePassword, isSuccess, isError, error } = useChangePassword();

  console.log({ isSuccess, isError, error });

  const handleFormSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault();
    if (isError) {
      //@ts-ignore
      toast.error(error?.message);
    }
    if (newPassword === confirmedPassword) {
      return await changePassword(confirmedPassword);
    } else if (newPassword !== confirmedPassword) {
      toast.error("The passwords does not match!!");
    } else if (isSuccess) {
      toast.success("Password Successfully Changed.");
    }
  };
  return (
    <>
      <Toaster />
      <Head>
        <title>Let&apos;s Link | About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />

      <Grid.Container gap={2} justify="center">
        <Grid xs={6} justify={"center"}>
          <Card css={{ justifyContent: "center", alignItems: "center" }}>
            <Card.Header css={{ justifyContent: "center", py: 30 }}>
              <Text h3>Change Password</Text>
            </Card.Header>
            <form onSubmit={handleFormSubmit}>
              <Input.Password
                bordered
                fullWidth
                color="primary"
                size="lg"
                placeholder="New Password"
                onChange={(e) => setNewPassword(e.target.value)}
                css={{ mb: 20 }}
              />

              <Input.Password
                bordered
                fullWidth
                color="primary"
                size="lg"
                placeholder="Confirm Password"
                onChange={(e) => setConfirmedPassword(e.target.value)}
                css={{ mb: 20 }}
              />

              <Row justify="center">
                <Button type="submit" color="secondary" shadow>
                  Submit
                </Button>
              </Row>
            </form>
          </Card>
        </Grid>
        <Grid xs={6}>
          <LoginSvg />
        </Grid>
      </Grid.Container>
    </>
  );
};

export default ChangePassword;
